name: Terraform Code Checks

description: A GitHub Action to perform Terraform code checks including formatting, linting, and security checks.

inputs:
  soft_fail:
    description: "Set to true for soft fail on Checkov"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout Terraform code
      uses: actions/checkout@v3

    - name: Run terraform fmt
      run: terraform fmt -check

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4

    - name: Run TFLint
      shell: bash
      run: tflint -f compact

    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v12
      with:
        soft_fail: ${{ inputs.soft_fail }}
