name: Build and Publish Docker Image

on:
  push:
    # branches:
    #   - main

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout app code
        uses: actions/checkout@v2
        with:
          repository: hello-umi/sre-challenge
          path: ./src
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          cd ./src
          docker build \
            --build-arg NODE_ENV=production \
            -t ghcr.io/${{ github.repository }}/sre-challenge-app:latest \
            -f Dockerfile .

      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/sre-challenge-app:latest
