name: Build and Publish Docker Image

on: push

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Build and Publish Docker Image
        uses: ./.github/actions/build
        with:
          repository: hello-umi/sre-challenge
          ref: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
