name: Build and Publish Docker Image

on:
  push:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout app code
        uses: actions/checkout@v2
        with:
          repository: hello-umi/sre-challenge
          path: ./src
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Checkov GitHub Action
      #   uses: bridgecrewio/checkov-action@v12
      #   with:
      #     soft_fail: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          cd ./src
          docker build \
            --build-arg NODE_ENV=production \
            -t ghcr.io/${{ github.repository }}/sre-challenge-app:${{ github.sha }} \
            -f Dockerfile .

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@0.20.0
      #   with:
      #     image-ref: ghcr.io/${{ github.repository }}/sre-challenge-app:${{ github.sha }}
      #     format: 'table'
      #     exit-code: '1'
      #     ignore-unfixed: true
      #     vuln-type: 'os,library'
      #     severity: 'CRITICAL,HIGH'

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          issue-title: "Tag ghcr.io/${{ github.repository }}/sre-challenge-app:${{ github.sha }} as latest"
          issue-body: "Do you want to tag ghcr.io/${{ github.repository }}/sre-challenge-app:${{ github.sha }} as ghcr.io/${{ github.repository }}/sre-challenge-app:latest"
          exclude-workflow-initiator-as-approver: false

      - name: Push the Docker image
        run: |
          docker tag ghcr.io/${{ github.repository }}/sre-challenge-app:${{ github.sha }} ghcr.io/${{ github.repository }}/sre-challenge-app:latest
          docker push ghcr.io/${{ github.repository }}/sre-challenge-app:latest
