name: Terraform code checks

on: push

jobs:
  check-tf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Terraform code
        uses: actions/checkout@v2

      - name: Run terraform fmt
        run: terraform fmt -check

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: tflint -f compact

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          soft_fail: true
