name: Promote to latest and deploy to PROD

on:
  push:
    # branches:
    # - main

permissions:
  contents: read
  issues: write
  packages: write
  attestations: write
  id-token: write

jobs:
  input:
    name: User Approval needed
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.actor }}
          minimum-approvals: 1
          issue-title: "Deploying ${{ github.sha }} to prod"
          issue-body: "Approve or deny the deployment of ${{ github.sha }} to prod."
          exclude-workflow-initiator-as-approver: false

  promote:
    name: Promote ghcr.io/${{ github.repository }}/sre-challenge-app:${{ github.sha }} to latest and deploy to PROD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3

      - name: Build and publish ${{ github.sha }}
        uses: ./.github/actions/build
        with:
          repository: hello-umi/sre-challenge
          ref: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tagging ${{ github.sha }} as lastest
        run: |
          docker pull ghcr.io/${{ github.repository }}/sre-challenge-app:${{ github.sha }}
          docker tag ghcr.io/${{ github.repository }}/sre-challenge-app:${{ github.sha }} ghcr.io/${{ github.repository }}/sre-challenge-app:latest
          docker push ghcr.io/${{ github.repository }}/sre-challenge-app:latest

  gcp-deploy:
    name: Deploy ghcr.io/${{ github.repository }}/sre-challenge-app:${{ github.sha }} to GKE
    needs: [promote]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: install google-cloud-sdk-gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Terraform init and validate
        run: |
          terraform init
          terraform validate

      - name: Terraform plan
        run: |
          terraform plan -var sha=${{ github.sha }} -out /tmp/${{ github.sha }}

      - name: Terraform apply
        run: |
          terraform apply /tmp/${{ github.sha }} -auto-approve
